// <auto-generated />
namespace TimeSheet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Admin_company_parameters_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Admin_company_parameters_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704060602515_Admin_company_parameters_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
